"""initial_schema

Revision ID: 149adcd94073
Revises: 
Create Date: 2026-02-26 10:40:40.626828
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '149adcd94073'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_replied', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', name='campaignstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_venue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'researching', 'matched', 'drafted', 'sent', 'replied', name='leadstatus'), nullable=False),
    sa.Column('initial_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreachmetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('sent_this_hour', sa.Integer(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unsubscribedemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unsubscribe_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unsubscribedemail_email_address'), 'unsubscribedemail', ['email_address'], unique=False)
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('lead_count_discovered', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone_adapted_for', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mcq_answers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('drafted', 'approved', 'sent', 'bounced', 'opened', name='emailstatus'), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelbrief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_signals', sa.JSON(), nullable=True),
    sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('talking_points', sa.JSON(), nullable=True),
    sa.Column('company_product_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('value_proposition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_email_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for_day', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'skipped', name='followupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup')
    op.drop_table('match')
    op.drop_table('intelbrief')
    op.drop_table('email')
    op.drop_table('venue')
    op.drop_table('userprofile')
    op.drop_index(op.f('ix_unsubscribedemail_email_address'), table_name='unsubscribedemail')
    op.drop_table('unsubscribedemail')
    op.drop_table('outreachmetric')
    op.drop_table('lead')
    op.drop_table('campaign')
    op.drop_table('agentlog')
    # ### end Alembic commands ###
